In [1]:
import pandas as pd

In [2]:
net=pd.read_csv("/content/netflix_advanced_dataset.csv")
net

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s00000,Movie,Title 0,Director D,"Actor X, Actor Y",United Kingdom,2020-07-22 14:20:51,1954,TV-PG,30 min,Action,Sample description of the content.
1,s00001,TV Show,Title 1,Director C,"Actor M, Actor N",United Kingdom,2022-06-03 21:53:37,1991,TV-MA,14 Seasons,Documentary,Sample description of the content.
2,s00002,Movie,Title 2,Director B,"Actor X, Actor Y",South Korea,2023-03-04 12:17:51,2010,NC-17,84 min,Action,Sample description of the content.
3,s00003,Movie,Title 3,Director A,"Actor M, Actor N",United States,2020-02-24 13:31:46,1971,TV-MA,113 min,Comedy,Sample description of the content.
4,s00004,Movie,Title 4,Director B,"Actor X, Actor Y",South Korea,2021-08-28 11:14:33,1970,TV-PG,25 min,Action,Sample description of the content.
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,s01195,Movie,Title 1195,Director B,"Actor M, Actor N",United States,2017-09-20 13:27:43,1991,PG-13,30 min,Sci-Fi,Sample description of the content.
1196,s01196,TV Show,Title 1196,Director D,"Actor M, Actor N",India,2022-08-26 15:11:59,1981,NC-17,14 Seasons,Drama,Sample description of the content.
1197,s01197,Movie,Title 1197,Director B,"Actor M, Actor N",Canada,2023-08-26 09:07:41,1988,PG,101 min,Romance,Sample description of the content.
1198,s01198,Movie,Title 1198,Director A,"Actor M, Actor N",India,2019-01-14 10:56:43,1985,TV-PG,25 min,Romance,Sample description of the content.
1199,s01199,Movie,Title 1199,Director C,"Actor X, Actor Y",United Kingdom,2022-09-13 07:00:45,1985,TV-PG,112 min,Drama,Sample description of the content.

In [15]:
net['type'].value_counts()

type
Movie      601
TV Show    599
Name: count, dtype: int64

In [19]:
print("Total number of movies")
movies=net[net["type"]=="Movie"]
len(movies)

Total number of movies

601

In [29]:
movies=net[(net["type"]=="Movie") & (net["release_year"]>2020)]
print("Movie released after 2020")
movies

Movie released after 2020

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
131,s00131,Movie,Title 131,Director A,"Actor X, Actor Y",United States,2019-01-29 08:27:32,2022,R,183 min,Drama,Sample description of the content.
134,s00134,Movie,Title 134,Director D,"Actor M, Actor N",Japan,2021-09-28 16:38:42,2024,G,72 min,Horror,Sample description of the content.
154,s00154,Movie,Title 154,Director C,"Actor M, Actor N",Canada,2018-04-25 15:10:00,2021,PG-13,142 min,Documentary,Sample description of the content.
168,s00168,Movie,Title 168,Director C,"Actor A, Actor B",Japan,2020-12-22 04:42:14,2021,TV-MA,136 min,Documentary,Sample description of the content.
247,s00247,Movie,Title 247,Director D,"Actor X, Actor Y",United States,2020-02-17 15:12:10,2021,G,122 min,Sci-Fi,Sample description of the content.
340,s00340,Movie,Title 340,Director B,"Actor M, Actor N",United States,2019-08-15 01:38:44,2023,PG,157 min,Horror,Sample description of the content.
351,s00351,Movie,Title 351,Director A,"Actor M, Actor N",United Kingdom,2021-03-28 09:50:26,2021,TV-MA,64 min,Horror,Sample description of the content.
368,s00368,Movie,Title 368,Director B,"Actor M, Actor N",Canada,2023-09-26 13:09:10,2023,TV-14,187 min,Horror,Sample description of the content.
394,s00394,Movie,Title 394,Director D,"Actor A, Actor B",Canada,2018-04-14 13:14:06,2023,PG-13,35 min,Sci-Fi,Sample description of the content.
402,s00402,Movie,Title 402,Director B,"Actor A, Actor B",Canada,2019-01-05 04:00:16,2022,PG-13,59 min,Comedy,Sample description of the content.
459,s00459,Movie,Title 459,Director C,"Actor M, Actor N",United States,2021-10-12 23:19:55,2022,TV-PG,85 min,Romance,Sample description of the content.
463,s00463,Movie,Title 463,Director D,"Actor X, Actor Y",United Kingdom,2023-09-09 10:11:27,2022,PG-13,145 min,Horror,Sample description of the content.
492,s00492,Movie,Title 492,Director C,"Actor X, Actor Y",Japan,2023-08-30 14:16:19,2021,PG-13,48 min,Horror,Sample description of the content.
512,s00512,Movie,Title 512,Director A,"Actor A, Actor B",United Kingdom,2023-10-21 03:10:15,2021,PG-13,135 min,Documentary,Sample description of the content.
571,s00571,Movie,Title 571,Director B,"Actor A, Actor B",India,2022-11-02 05:55:26,2022,TV-14,143 min,Romance,Sample description of the content.
592,s00592,Movie,Title 592,Director C,"Actor A, Actor B",India,2022-10-03 02:57:04,2021,G,99 min,Romance,Sample description of the content.
596,s00596,Movie,Title 596,Director B,"Actor M, Actor N",United Kingdom,2023-05-28 01:01:06,2023,TV-MA,188 min,Documentary,Sample description of the content.
616,s00616,Movie,Title 616,Director A,"Actor M, Actor N",United Kingdom,2018-01-13 11:20:33,2022,TV-PG,184 min,Comedy,Sample description of the content.
726,s00726,Movie,Title 726,Director C,"Actor X, Actor Y",United Kingdom,2017-10-21 22:32:26,2024,TV-PG,120 min,Horror,Sample description of the content.
737,s00737,Movie,Title 737,Director B,"Actor X, Actor Y",Canada,2023-07-20 16:54:11,2024,TV-PG,17 min,Drama,Sample description of the content.
797,s00797,Movie,Title 797,Director D,"Actor A, Actor B",Japan,2017-10-30 03:00:39,2021,TV-14,118 min,Documentary,Sample description of the content.
800,s00800,Movie,Title 800,Director A,"Actor M, Actor N",South Korea,2019-01-10 11:16:36,2021,R,53 min,Drama,Sample description of the content.
820,s00820,Movie,Title 820,Director B,"Actor A, Actor B",India,2023-05-24 04:39:27,2023,NC-17,12 min,Romance,Sample description of the content.
845,s00845,Movie,Title 845,Director C,"Actor M, Actor N",South Korea,2021-03-07 06:26:55,2021,PG-13,165 min,Drama,Sample description of the content.
850,s00850,Movie,Title 850,Director B,"Actor M, Actor N",United Kingdom,2023-01-17 08:46:49,2024,NC-17,55 min,Sci-Fi,Sample description of the content.
949,s00949,Movie,Title 949,Director A,"Actor A, Actor B",South Korea,2020-02-29 09:42:11,2023,R,141 min,Romance,Sample description of the content.
971,s00971,Movie,Title 971,Director C,"Actor A, Actor B",Canada,2017-08-27 08:51:13,2022,TV-PG,64 min,Action,Sample description of the content.
1011,s01011,Movie,Title 1011,Director A,"Actor X, Actor Y",South Korea,2023-07-17 03:10:25,2023,NC-17,171 min,Comedy,Sample description of the content.
1017,s01017,Movie,Title 1017,Director A,"Actor A, Actor B",United Kingdom,2021-09-20 23:15:40,2021,TV-PG,86 min,Romance,Sample description of the content.
1038,s01038,Movie,Title 1038,Director A,"Actor X, Actor Y",United States,2017-09-07 13:18:07,2022,NC-17,101 min,Documentary,Sample description of the content.
1040,s01040,Movie,Title 1040,Director B,"Actor X, Actor Y",Canada,2020-02-24 14:50:15,2024,R,121 min,Sci-Fi,Sample description of the content.
1047,s01047,Movie,Title 1047,Director C,"Actor X, Actor Y",Japan,2018-02-20 14:12:26,2024,PG-13,9 min,Comedy,Sample description of the content.
1063,s01063,Movie,Title 1063,Director B,"Actor M, Actor N",India,2022-07-10 09:17:52,2021,PG-13,99 min,Romance,Sample description of the content.
1070,s01070,Movie,Title 1070,Director C,"Actor X, Actor Y",Japan,2019-04-10 05:59:48,2021,TV-14,173 min,Comedy,Sample description of the content.
1116,s01116,Movie,Title 1116,Director A,"Actor A, Actor B",United States,2019-08-14 11:43:03,2024,G,154 min,Comedy,Sample description of the content.
1118,s01118,Movie,Title 1118,Director A,"Actor M, Actor N",India,2021-12-13 06:18:18,2023,TV-14,133 min,Documentary,Sample description of the content.
1146,s01146,Movie,Title 1146,Director C,"Actor X, Actor Y",Canada,2018-09-01 22:00:30,2021,TV-MA,164 min,Drama,Sample description of the content.
1157,s01157,Movie,Title 1157,Director C,"Actor M, Actor N",Canada,2019-10-09 14:34:34,2023,TV-14,116 min,Drama,Sample description of the content.
1161,s01161,Movie,Title 1161,Director A,"Actor X, Actor Y",India,2021-03-04 12:12:22,2023,G,95 min,Drama,Sample description of the content.

In [35]:
oldest_movie=net[(net["type"]=="Movie")&(net["release_year"].min())]
print("Oldest movie is ")
oldest_movie

Oldest movie is

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [36]:
old_movie=net[net["release_year"]==net["release_year"].min()]
print("Oldest movie is ")
old_movie

Oldest movie is

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6,s00006,Movie,Title 6,Director A,"Actor M, Actor N",South Korea,2023-02-19 00:01:19,1950,TV-MA,88 min,Sci-Fi,Sample description of the content.
23,s00023,TV Show,Title 23,Director D,"Actor X, Actor Y",South Korea,2021-10-14 19:22:58,1950,TV-PG,14 Seasons,Sci-Fi,Sample description of the content.
110,s00110,TV Show,Title 110,Director B,"Actor X, Actor Y",South Korea,2018-08-24 20:19:34,1950,TV-PG,6 Seasons,Comedy,Sample description of the content.
148,s00148,Movie,Title 148,Director A,"Actor M, Actor N",United Kingdom,2019-08-31 11:56:08,1950,NC-17,193 min,Comedy,Sample description of the content.
256,s00256,Movie,Title 256,Director A,"Actor X, Actor Y",Canada,2020-09-19 16:31:57,1950,TV-MA,75 min,Drama,Sample description of the content.
262,s00262,Movie,Title 262,Director C,"Actor A, Actor B",Japan,2023-08-31 22:58:22,1950,R,121 min,Comedy,Sample description of the content.
311,s00311,Movie,Title 311,Director D,"Actor X, Actor Y",United Kingdom,2018-05-12 01:24:10,1950,PG-13,195 min,Drama,Sample description of the content.
326,s00326,Movie,Title 326,Director D,"Actor X, Actor Y",United Kingdom,2020-07-10 08:29:52,1950,TV-14,152 min,Comedy,Sample description of the content.
333,s00333,Movie,Title 333,Director C,"Actor X, Actor Y",Japan,2023-06-04 12:01:44,1950,TV-14,196 min,Action,Sample description of the content.
378,s00378,TV Show,Title 378,Director B,"Actor X, Actor Y",South Korea,2019-06-22 16:26:07,1950,NC-17,11 Seasons,Comedy,Sample description of the content.
466,s00466,TV Show,Title 466,Director D,"Actor M, Actor N",India,2017-11-09 04:32:41,1950,G,6 Seasons,Comedy,Sample description of the content.
754,s00754,TV Show,Title 754,Director D,"Actor M, Actor N",United Kingdom,2020-04-25 01:25:45,1950,PG,2 Seasons,Horror,Sample description of the content.
951,s00951,TV Show,Title 951,Director A,"Actor M, Actor N",United States,2022-01-17 20:51:23,1950,PG,14 Seasons,Romance,Sample description of the content.
956,s00956,TV Show,Title 956,Director D,"Actor A, Actor B",India,2020-02-01 00:52:03,1950,TV-14,13 Seasons,Comedy,Sample description of the content.
976,s00976,TV Show,Title 976,Director A,"Actor M, Actor N",United Kingdom,2019-02-09 16:21:54,1950,TV-MA,12 Seasons,Romance,Sample description of the content.
1002,s01002,Movie,Title 1002,Director C,"Actor M, Actor N",United Kingdom,2022-12-25 17:03:25,1950,NC-17,8 min,Comedy,Sample description of the content.
1021,s01021,Movie,Title 1021,Director D,"Actor A, Actor B",United Kingdom,2022-12-16 21:57:13,1950,R,137 min,Comedy,Sample description of the content.
1048,s01048,Movie,Title 1048,Director A,"Actor M, Actor N",United States,2020-10-31 12:44:57,1950,G,182 min,Romance,Sample description of the content.
1133,s01133,Movie,Title 1133,Director C,"Actor M, Actor N",United Kingdom,2018-01-22 15:12:36,1950,TV-MA,46 min,Romance,Sample description of the content.

In [38]:
print("number of oldest movies")
len(old_movie)

number of oldest movies

19

In [51]:
country_count=net['country'].value_counts()
print("Counting movies by country ")
country_count

Counting movies by country

country
United Kingdom    215
South Korea       211
United States     209
Japan             193
India             189
Canada            183
Name: count, dtype: int64

In [54]:
print("Top 10 directors ")
net['director'].head(10)

Top 10 directors

0    Director D
1    Director C
2    Director B
3    Director A
4    Director B
5    Director B
6    Director A
7    Director B
8    Director C
9    Director D
Name: director, dtype: object

In [64]:
longest_movie = net[net['duration'] == net['duration'].max()]
longest_movie

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
152,s00152,Movie,Title 152,Director C,"Actor A, Actor B",United States,2023-10-05 05:37:57,2009,TV-MA,99 min,Drama,Sample description of the content.
592,s00592,Movie,Title 592,Director C,"Actor A, Actor B",India,2022-10-03 02:57:04,2021,G,99 min,Romance,Sample description of the content.
1063,s01063,Movie,Title 1063,Director B,"Actor M, Actor N",India,2022-07-10 09:17:52,2021,PG-13,99 min,Romance,Sample description of the content.
1106,s01106,Movie,Title 1106,Director A,"Actor A, Actor B",United Kingdom,2018-01-20 17:16:25,1977,NC-17,99 min,Action,Sample description of the content.

In [65]:
print("Number of longest movies")
len(longest_movie)

Number of longest movies

4

In [68]:
sorted_movies = net.sort_values(by='release_year', ascending=True)
sorted_movies

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
951,s00951,TV Show,Title 951,Director A,"Actor M, Actor N",United States,2022-01-17 20:51:23,1950,PG,14 Seasons,Romance,Sample description of the content.
956,s00956,TV Show,Title 956,Director D,"Actor A, Actor B",India,2020-02-01 00:52:03,1950,TV-14,13 Seasons,Comedy,Sample description of the content.
311,s00311,Movie,Title 311,Director D,"Actor X, Actor Y",United Kingdom,2018-05-12 01:24:10,1950,PG-13,195 min,Drama,Sample description of the content.
326,s00326,Movie,Title 326,Director D,"Actor X, Actor Y",United Kingdom,2020-07-10 08:29:52,1950,TV-14,152 min,Comedy,Sample description of the content.
1133,s01133,Movie,Title 1133,Director C,"Actor M, Actor N",United Kingdom,2018-01-22 15:12:36,1950,TV-MA,46 min,Romance,Sample description of the content.
...,...,...,...,...,...,...,...,...,...,...,...,...
1116,s01116,Movie,Title 1116,Director A,"Actor A, Actor B",United States,2019-08-14 11:43:03,2024,G,154 min,Comedy,Sample description of the content.
134,s00134,Movie,Title 134,Director D,"Actor M, Actor N",Japan,2021-09-28 16:38:42,2024,G,72 min,Horror,Sample description of the content.
850,s00850,Movie,Title 850,Director B,"Actor M, Actor N",United Kingdom,2023-01-17 08:46:49,2024,NC-17,55 min,Sci-Fi,Sample description of the content.
76,s00076,TV Show,Title 76,Director D,"Actor A, Actor B",United Kingdom,2021-02-21 10:22:23,2024,PG-13,5 Seasons,Sci-Fi,Sample description of the content.
89,s00089,TV Show,Title 89,Director B,"Actor A, Actor B",United States,2020-08-10 22:06:09,2024,NC-17,2 Seasons,Documentary,Sample description of the content.

In [70]:
comedy_movies = net[net['listed_in'] == "Comedy"]
comedy_movies

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
3,s00003,Movie,Title 3,Director A,"Actor M, Actor N",United States,2020-02-24 13:31:46,1971,TV-MA,113 min,Comedy,Sample description of the content.
12,s00012,Movie,Title 12,Director C,"Actor A, Actor B",United States,2020-04-17 09:43:45,1994,TV-14,83 min,Comedy,Sample description of the content.
14,s00014,TV Show,Title 14,Director D,"Actor A, Actor B",India,2022-08-25 17:08:01,2022,PG-13,3 Seasons,Comedy,Sample description of the content.
17,s00017,TV Show,Title 17,Director D,"Actor M, Actor N",India,2018-12-04 21:26:06,2005,NC-17,3 Seasons,Comedy,Sample description of the content.
27,s00027,TV Show,Title 27,Director D,"Actor A, Actor B",Canada,2023-05-08 21:27:08,2005,TV-14,7 Seasons,Comedy,Sample description of the content.
...,...,...,...,...,...,...,...,...,...,...,...,...
1158,s01158,TV Show,Title 1158,Director A,"Actor A, Actor B",India,2020-05-13 10:40:34,1967,TV-MA,7 Seasons,Comedy,Sample description of the content.
1163,s01163,TV Show,Title 1163,Director D,"Actor A, Actor B",United States,2022-05-04 06:46:08,2018,PG-13,5 Seasons,Comedy,Sample description of the content.
1168,s01168,Movie,Title 1168,Director B,"Actor A, Actor B",India,2019-07-28 22:02:43,1971,PG,188 min,Comedy,Sample description of the content.
1181,s01181,TV Show,Title 1181,Director D,"Actor A, Actor B",South Korea,2017-07-30 13:17:34,2013,TV-PG,3 Seasons,Comedy,Sample description of the content.
1187,s01187,Movie,Title 1187,Director A,"Actor A, Actor B",Japan,2022-04-15 11:58:15,1988,TV-PG,38 min,Comedy,Sample description of the content.

In [71]:
print("Number of comedy movies")
len(comedy_movies)

Number of comedy movies

165

In [73]:
print('Adding new column as decade')
net['decade'] = (net['release_year'] // 10) * 10
net

Adding new column as decade

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,decade
0,s00000,Movie,Title 0,Director D,"Actor X, Actor Y",United Kingdom,2020-07-22 14:20:51,1954,TV-PG,30 min,Action,Sample description of the content.,1950
1,s00001,TV Show,Title 1,Director C,"Actor M, Actor N",United Kingdom,2022-06-03 21:53:37,1991,TV-MA,14 Seasons,Documentary,Sample description of the content.,1990
2,s00002,Movie,Title 2,Director B,"Actor X, Actor Y",South Korea,2023-03-04 12:17:51,2010,NC-17,84 min,Action,Sample description of the content.,2010
3,s00003,Movie,Title 3,Director A,"Actor M, Actor N",United States,2020-02-24 13:31:46,1971,TV-MA,113 min,Comedy,Sample description of the content.,1970
4,s00004,Movie,Title 4,Director B,"Actor X, Actor Y",South Korea,2021-08-28 11:14:33,1970,TV-PG,25 min,Action,Sample description of the content.,1970
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,s01195,Movie,Title 1195,Director B,"Actor M, Actor N",United States,2017-09-20 13:27:43,1991,PG-13,30 min,Sci-Fi,Sample description of the content.,1990
1196,s01196,TV Show,Title 1196,Director D,"Actor M, Actor N",India,2022-08-26 15:11:59,1981,NC-17,14 Seasons,Drama,Sample description of the content.,1980
1197,s01197,Movie,Title 1197,Director B,"Actor M, Actor N",Canada,2023-08-26 09:07:41,1988,PG,101 min,Romance,Sample description of the content.,1980
1198,s01198,Movie,Title 1198,Director A,"Actor M, Actor N",India,2019-01-14 10:56:43,1985,TV-PG,25 min,Romance,Sample description of the content.,1980
1199,s01199,Movie,Title 1199,Director C,"Actor X, Actor Y",United Kingdom,2022-09-13 07:00:45,1985,TV-PG,112 min,Drama,Sample description of the content.,1980

In [74]:
import numpy as np

In [85]:
d=net['duration'].to_numpy()
print("Array")
d

Array

array(['30 min', '14 Seasons', '84 min', ..., '101 min', '25 min',
       '112 min'], dtype=object)

In [93]:
print(d)
print(type(d))

['30 min' '14 Seasons' '84 min' ... '101 min' '25 min' '112 min']
<class 'numpy.ndarray'>